name: xeus-robot
channels:
  - conda-forge
dependencies:
  # Builde dependencies
  - cmake
  # Host dependencies
  - xeus-python==0.9.1
  - xtl
  - cppzmq
  - nlohmann_json
  - pybind11 
  - pybind11_json
  - pip
  - robotframework
  # Test dependencies
  - pytest
  - jupyter_kernel_test

