jobs:
  - job: 'Linux'
    strategy:
      matrix:
        py37:
          py_version: 3.7
        py38:
          py_version: 3.8
        py39:
          py_version: 3.9
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 360
    steps:
          
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - template: unix-build.yml
        parameters:
          platform: 'Linux'
